use std::env;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    let git_describe = std::process::Command::new("git")
        .args([
            "-C",
            manifest_dir.to_str().unwrap(),
            "describe",
            "--always",
            "--dirty",
            "--tags",
        ])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".into());

    let git_branch = std::process::Command::new("git")
        .args([
            "-C",
            manifest_dir.to_str().unwrap(),
            "rev-parse",
            "--abbrev-ref",
            "HEAD",
        ])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".into());

    let fw_id = format!("{git_branch}@{git_describe}");
    println!("cargo:rustc-env=FIRMWARE_ID={fw_id}");
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/index");

    // CANbossTouch: LVGL-Screen-Tabellen aus den EDS-Dateien generieren
    // (Rust-Port von CANbossTouch tools/eds2lvgl.py). Der Codegen liegt in
    // build_codegen.rs und wird vom Host-Port (canboss-touch-host) geteilt.
    generate_canboss_tables(&manifest_dir.join("eds"));

    // memory.x is generated by embassy-stm32's `memory-x` feature.
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}

include!("build_codegen.rs");
